## Wallmart Sales Data

In [1]:

# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:

data = pd.read_csv("Walmart.csv", encoding_errors='ignore')

data.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [3]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [4]:
# Changing Column names to all lowercase.

data.columns = data.columns.str.lower()

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   branch          10051 non-null  object
 2   city            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

- unit_price should be in float/integer
- date and time coloumn can be converted to date and time column respectively
- unit_price and quantity contains null values

In [6]:

data['unit_price'] = data['unit_price'].str.replace('$','').astype(float)

# Converted unit price to float datatype by removing the '$' sign first.

In [21]:

data['date'] = pd.to_datetime(data['date'])
data['time'] = pd.to_datetime(data['time'], format='%H:%M:%S').dt.time

# Converted date and time column to their appropriate datatypes.

In [22]:
(data.isnull().sum()/data.count())*100

invoice_id        0.0
branch            0.0
city              0.0
category          0.0
unit_price        0.0
quantity          0.0
date              0.0
time              0.0
payment_method    0.0
rating            0.0
profit_margin     0.0
dtype: float64

Null values in the column compromises of only 0.3% which is negligble. So, it is best to drop the null values in this case.

In [23]:

data.dropna(inplace=True)

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   branch          9969 non-null   object
 2   city            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   datetime64[ns]
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(5)
memory usage: 934.6+ KB

In [25]:
#  Let's check for the duplicate values

data.duplicated().sum()

np.int64(0)

There are 51 duplicate values in the dataset.

In [26]:

data.drop_duplicates(inplace=True)

In [28]:

# Creating new column from already existing columns.

data['revenue'] = data['unit_price'] * data['quantity']

In [30]:

data.head(5)

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,revenue
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,2019-05-01,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,2019-08-03,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,2019-03-03,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,2019-01-27,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,2019-08-02,10:37:00,Ewallet,5.3,0.48,604.17

In [31]:

data.to_csv("Cleaned_Walmart_Dataset.csv", index=False)

In [32]:
# Toolkit for importing data to SQL  |  Importing Dependencies

import pymysql          #  (Work as an adapter)
from sqlalchemy import create_engine    #     (Creating connection with mySQL)

- host: localhost
- port: 3306
- user: root
- password: mySQL123

In [35]:

# Making Connections

engine = create_engine("mysql+pymysql://root:mySQL123@localhost:3306/wallmart_db")


try:
    engine
    print("Connection Successful")
except:
    print("Connection Unsuccessful")

Connection Successful

In [ ]:

data.to_sql(name='wallmart_sales', con=engine, if_exists='append', index=False)

# Created Wallmart_Sales table in mySQL and uploaded this cleaned data to the table.

9969

### ---  End   ---